In [1]:
import numpy as np
import cv2
from stereovision.calibration import StereoCalibrator, StereoCalibration

In [7]:
calib = StereoCalibration()
# 相机内参
l_cam_mat = np.array([[642.4922, 0, 309.1599], [0, 644.0784, 231.4226], [0, 0, 1]])
r_cam_mat = np.array([[642.0054, 0, 323.7684], [0, 643.1802, 228.1761], [0, 0, 1]])
# 径向畸变
l_dist = np.array([[-0.000699168, 0.0836996, 0, 0, 0]])
r_dist = np.array([[0.01518, -0.008996, 0, 0, 0]])
# 旋转矩阵
rot_mat = np.array([[0.99988, -0.010141, 0.01135],
                    [0.010104, 0.99994, 0.0032789],
                    [-0.01138, -0.00316379, 0.99993]])
# rot_mat = rot_mat.T
# 平移向量
trans_vec = np.array([[-56.14931], [0.04385568], [-0.6910189]])
# Essential Matrix
e_mat = np.array([[-0.0065098, 0.6911237, 0.041666],
                  [-0.0536346, 0.177123, 56.15326],
                  [0.525559, -56.1466, 0.1781438]])
# Fundamental Matrix
f_mat = np.array([[-1.5782e-08, 1.6713925e-06, -0.000317],
                  [-1.29791e-07, 4.275669e-07, 0.0872468],
                  [0.00085272, -0.087812, 0.2941864]])


In [8]:
(calib.rect_trans["left"], calib.rect_trans["right"],
 calib.proj_mats["left"], calib.proj_mats["right"],
 calib.disp_to_depth_mat, calib.valid_boxes["left"],
 calib.valid_boxes["right"]) = cv2.stereoRectify(calib.cam_mats["left"],
                                                 calib.dist_coefs["left"],
                                                 calib.cam_mats["right"],
                                                 calib.dist_coefs["right"],
                                                 (640, 480),
                                                 calib.rot_mat,
                                                 calib.trans_vec,
                                                 flags=0)
for side in ("left", "right"):
    (calib.undistortion_map[side],
        calib.rectification_map[side]) = cv2.initUndistortRectifyMap(
        calib.cam_mats[side],
        calib.dist_coefs[side],
        calib.rect_trans[side],
        calib.proj_mats[side],
        (640, 480),
        cv2.CV_32FC1)

In [9]:
calib.export('calibrate/4')

In [2]:
# dist_coefs_left = np.load('calibrate/2/dist_coefs_left.npy')
# dist_coefs_right = np.load('calibrate/2/dist_coefs_right.npy')
# print(dist_coefs_left)
# print(dist_coefs_right)
l = np.load('calibrate/3/cam_mats_left.npy')
print(l)
r = np.load('calibrate/3/cam_mats_right.npy')
print(r)
# Q = np.load('calibrate/3/disp_to_depth_mat.npy')
# print(Q)

[[642.4922   0.     309.1599]
 [  0.     644.0784 231.4226]
 [  0.       0.       1.    ]]
[[642.0054   0.     323.7684]
 [  0.     643.1802 228.1761]
 [  0.       0.       1.    ]]
